In [6]:
import numpy as np
import pandas as pd
import numpy.linalg as la

### 3

In [7]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def cost_function(theta, x, y):
    m = len(y)
    h = sigmoid(np.dot(X, theta))
    J = -(1/m) * np.sum(y * np.log(h) + (1-y) * np.log(1-h))
    grad = (1/m) * np.dot(X.T, (h-y))
    return J, grad

def gradient_descent(X, y, theta, alpha, num_iters):
    m = len(y)
    
    for i in range(num_iters):
        cost, grad = cost_function(theta, X, y)
        theta = theta - alpha * grad
        
    return theta

In [8]:
X = np.array([1.1, 4.1, 2.7, 3.9, 7.1, 1.3, 9.7, 0.7, 3.4, 6.0]).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0]).reshape(-1, 1)

X = np.hstack((np.ones((len(X), 1)), X))

theta = np.zeros((2,1))
alpha = 0.01
num_iters = 1000
theta = gradient_descent(X, y, theta, alpha, num_iters)
print('theta:', theta)

theta: [[-1.19142978]
 [ 0.28527787]]


### 4

In [12]:
A0 = np.array([[3],
               [2],
               [5]])

W1 = np.array([[1.1, 1.3, 1.5],
               [0.1, 2.0, 1.7]
              ])

W2 = np.array([[2.0, 1.3],
               [1.2, 1.7]
              ])

print('W1:\n', W1)
print('\nW2:\n', W2)

A1 = W1.dot(A0)
A2 = W2.dot(A1)


print('\nA1:\n', A1)
print('\nA2:\n', A2)

W1:
 [[1.1 1.3 1.5]
 [0.1 2.  1.7]]

W2:
 [[2.  1.3]
 [1.2 1.7]]

A1:
 [[13.4]
 [12.8]]

A2:
 [[43.44]
 [37.84]]
